/**
 * Development setup: generates fresh secrets into server/api/.env.local and
 * the matching service configuration into dev/service.json (both
 * gitignored). Nothing secret is ever committed or hardcoded.
 *
 *   npm run dev:keys -w server/api            # keep existing keys
 *   npm run dev:keys -w server/api -- --force # rotate them
 */
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ed25519FromSeed } from "../security/keys.js";

const apiDir = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const repoDir = resolve(apiDir, "..", "..");
const envPath = join(apiDir, ".env.local");
const force = process.argv.includes("--force");

function readEnv(path: string): Record<string, string> {
  if (!existsSync(path)) return {};
  return Object.fromEntries(
    readFileSync(path, "utf8")
      .split(/\r?\n/)
      .filter((l) => l && !l.startsWith("#") && l.includes("="))
      .map((l) => [l.slice(0, l.indexOf("=")), l.slice(l.indexOf("=") + 1)]),
  );
}

const existing = force ? {} : readEnv(envPath);
const key = () => randomBytes(32).toString("base64");
const env = {
  NODE_ENV: "development",
  HOST: "127.0.0.1",
  PORT: "8787",
  DATABASE_URL: "pglite://.data/dev",
  ACCESS_TOKEN_SEED: existing.ACCESS_TOKEN_SEED ?? key(),
  RELAY_SIGNING_SEED: existing.RELAY_SIGNING_SEED ?? key(),
  RELAY_KEY_ID: existing.RELAY_KEY_ID ?? "dev-1",
  DATA_ENCRYPTION_KEY: existing.DATA_ENCRYPTION_KEY ?? key(),
  NODE_PROVISIONING: existing.NODE_PROVISIONING ?? "wireguard-demo",
};
writeFileSync(
  envPath,
  "# Generated by `npm run dev:keys`. Development only; never commit.\n" +
    Object.entries(env).map(([k, v]) => `${k}=${v}`).join("\n") +
    "\n",
);

const relay = ed25519FromSeed(env.RELAY_SIGNING_SEED);
const serviceJson = join(repoDir, "dev", "service.json");
mkdirSync(dirname(serviceJson), { recursive: true });
writeFileSync(
  serviceJson,
  JSON.stringify(
    {
      apiBaseUrl: `http://${env.HOST}:${env.PORT}`,
      allowInsecureApi: true,
      allowPrivateRelays: true,
      relayKeys: [{ id: env.RELAY_KEY_ID, publicKey: relay.publicKeyBase64 }],
    },
    null,
    2,
  ) + "\n",
);

console.log(`wrote ${envPath}`);
console.log(`wrote ${serviceJson} (relay key ${env.RELAY_KEY_ID}: ${relay.publicKeyBase64})`);
