import { existsSync } from "node:fs";
import { z } from "zod";

/**
 * All configuration comes from the environment. Secrets have no defaults:
 * development uses `.env.local` generated by `npm run dev:keys` (gitignored),
 * tests generate throwaway keys, production reads them from the platform's
 * secret store.
 */
const base64Key = z
  .string()
  .refine((v) => Buffer.from(v, "base64").length === 32, "must be 32 bytes, base64-encoded");

const Env = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  HOST: z.string().default("127.0.0.1"),
  PORT: z.coerce.number().int().min(1).max(65535).default(8787),
  PUBLIC_BASE_URL: z.string().url().default("http://127.0.0.1:8787"),
  TRUST_PROXY: z.stringbool().default(false),
  /** Per-IP request limits. Only tests turn this off. */
  RATE_LIMIT_ENABLED: z.stringbool().default(true),

  /** `postgres://…` in production; `pglite://<dir>` or `pglite://memory` for dev/tests. */
  DATABASE_URL: z.string().default("pglite://.data/dev"),

  /** Seeds of the Ed25519 keys (32 bytes, base64). */
  ACCESS_TOKEN_SEED: base64Key,
  RELAY_SIGNING_SEED: base64Key,
  RELAY_KEY_ID: z.string().min(1).default("fleet-1"),
  /** AES-256-GCM key for secrets at rest (TOTP seeds). */
  DATA_ENCRYPTION_KEY: base64Key,

  ACCESS_TOKEN_TTL_SECONDS: z.coerce.number().int().min(60).max(3600).default(900),
  REFRESH_TOKEN_TTL_DAYS: z.coerce.number().int().min(1).max(365).default(60),
  RELAY_LIST_TTL_MINUTES: z.coerce.number().int().min(10).default(360),

  /** How device peers reach nodes: `agent` (production) or the public WireGuard demo server (development only). */
  NODE_PROVISIONING: z.enum(["agent", "wireguard-demo"]).default("agent"),
  BILLING_PROVIDER: z.enum(["manual", "stripe"]).default("manual"),
  STRIPE_SECRET_KEY: z.string().optional(),
  STRIPE_WEBHOOK_SECRET: z.string().optional(),
  /** Stripe price ids (price_…) that sell each paid plan. */
  STRIPE_PRICE_MONTHLY: z.string().optional(),
  STRIPE_PRICE_ANNUAL: z.string().optional(),
  MAIL_TRANSPORT: z.enum(["console", "smtp"]).default("console"),
  SMTP_URL: z.string().optional(),
  GEOIP_PROVIDER: z.enum(["none", "maxmind"]).default("none"),
  MAXMIND_DB_PATH: z.string().optional(),
  UPLOAD_DIR: z.string().default(".data/uploads"),
});

export type Config = z.infer<typeof Env>;

export function loadConfig(env: NodeJS.ProcessEnv = process.env): Config {
  if (env === process.env && existsSync(".env.local") && env.NODE_ENV !== "production") {
    process.loadEnvFile(".env.local");
  }
  const parsed = Env.safeParse(env);
  if (!parsed.success) {
    const issues = parsed.error.issues.map((i) => `  ${i.path.join(".")}: ${i.message}`).join("\n");
    const hint =
      env.NODE_ENV === "production" ? "" : "\nFor local development run `npm run dev:keys -w server/api` first.";
    throw new Error(`Invalid configuration:\n${issues}${hint}`);
  }
  const cfg = parsed.data;
  if (cfg.NODE_ENV === "production") {
    const problems: string[] = [];
    if (cfg.DATABASE_URL.startsWith("pglite://")) problems.push("DATABASE_URL must be a PostgreSQL URL");
    if (cfg.NODE_PROVISIONING !== "agent") problems.push("NODE_PROVISIONING=wireguard-demo is development-only");
    if (!cfg.RATE_LIMIT_ENABLED) problems.push("rate limiting can't be disabled in production");
    if (cfg.MAIL_TRANSPORT === "console") problems.push("MAIL_TRANSPORT=console would drop real emails");
    if (!cfg.PUBLIC_BASE_URL.startsWith("https://")) problems.push("PUBLIC_BASE_URL must be https");
    if (cfg.BILLING_PROVIDER === "stripe") {
      if (!cfg.STRIPE_SECRET_KEY || !cfg.STRIPE_WEBHOOK_SECRET) problems.push("Stripe needs STRIPE_SECRET_KEY and STRIPE_WEBHOOK_SECRET");
      else if (!/^(sk|rk)_live_/.test(cfg.STRIPE_SECRET_KEY)) problems.push("STRIPE_SECRET_KEY is not a live key (sk_live_… or rk_live_…)");
      if (cfg.STRIPE_WEBHOOK_SECRET && !cfg.STRIPE_WEBHOOK_SECRET.startsWith("whsec_")) problems.push("STRIPE_WEBHOOK_SECRET must be the endpoint's whsec_… secret");
      if (!cfg.STRIPE_PRICE_MONTHLY || !cfg.STRIPE_PRICE_ANNUAL) problems.push("Stripe needs STRIPE_PRICE_MONTHLY and STRIPE_PRICE_ANNUAL");
    }
    if (problems.length) throw new Error(`Refusing to start in production:\n  ${problems.join("\n  ")}`);
  }
  return cfg;
}
